# 
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.password = "vagrant"

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-debian11"
    virtualbox.vm.box = "file://./builds/virtualbox-debian11.box"
  virtualbox.vm.network :public_network, bridge: "Ethernet"

    config.vm.provider :virtualbox do |v|
      v.name = "Jenkins Debian Slave"
      v.gui = false
      v.memory = 1024
      v.cpus = 1
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
    config.vm.provision "shell", inline: "ip a"
  end

end
