# 
Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.ssh.username = "jenkins"
  config.ssh.password = "jenkins"

  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "virtualbox-debian11"
    virtualbox.vm.box = "file://./builds//virtualbox-1726833817-66ed6659-a77c-4dd3-384c-61222e8554ab.box"
  virtualbox.vm.network :public_network, bridge: "enp7s0"

    config.vm.provider :virtualbox do |v|
      v.name = "Jenkins Debian Slave"
      v.gui = false
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
    config.vm.provision "shell", inline: "ip a"
  end

end
