Vagrant.configure("2") do |config|
  config.vm.communicator = "winrm" # Set the communicator to WinRM
  config.winrm.username = "Administrator"
  config.winrm.password = "jenkins"
  #config.winrm.transport = :plaintext # Specify the transport method
  config.winrm.basic_auth_only = true # Use basic authentication


  # VirtualBox.
  config.vm.define "virtualbox" do |virtualbox|
    virtualbox.vm.hostname = "windows-jenkins-slave"
    virtualbox.vm.box = "file://./builds/virtualbox-1726846567-66ed9969-660c-a246-b388-b5a475a607e9.box"
  virtualbox.vm.network :public_network, bridge: "enp7s0"

    config.vm.provider :virtualbox do |v|
      v.name = "Jenkins Windows Slave"
      v.gui = false
      v.memory = 2048
      v.cpus = 2
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
    end

    config.vm.provision "shell", inline: "echo Hello, World"
    config.vm.provision "shell", inline: "ipconfig"
  end

end
