---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install some helpful utilities.
      apt:
        name:
          - git
          - wget
          - curl
          - vim
          - openjdk-17-jdk
          - htop

        state: present
      when: ansible_os_family == 'Debian'
    - name: Download Jenkins agent.jar
      ansible.builtin.get_url:
        url: http://10.65.85.41:8080/jnlpJars/agent.jar
        dest: /home/vagrant/agent.jar
        mode: '0755'

    - name: Run Jenkins agent
      ansible.builtin.command: >
        java -jar /home/vagrant/agent.jar
        -url http://10.65.85.41:8080/
        -secret @/home/vagrant/secret-file
        -name "Debian Based Agent"
        -workDir "/home/vagrant"
      args:
        chdir: /home/vagrant
    - name: Create Jenkins agent service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/jenkins-agent.service
        content: |
          [Unit]
          Description=Jenkins Agent
          After=network.target

          [Service]
          User=vagrant
          WorkingDirectory=/home/vagrant
          ExecStart=/usr/bin/java -jar /home/vagrant/agent.jar -url http://10.65.85.41:8080/ -secret @/home/vagrant/secret-file -name "Debian Based Agent" -workDir "/home/vagrant"
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
    - name: Reload systemd to recognize the new service
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Enable Jenkins agent service to start on boot
      ansible.builtin.systemd:
        name: jenkins-agent
        enabled: yes
        state: started
